### ISSUE TITLE
Is this work on Near Blockchain

### ISSUE THREAD

**Issue by caelum0x** [vlmoon99/flutterchain#12]
Hi I am trying to build a mobile app on near blockchaşn but I can not find any resource on flutter nor react native except your repo.Where can I find documentetion

**Comment by vlmoon99** [comment]
Hi, if you have any question in the future write me in telegramm https://t.me/vlmoon99 , you can find general info here - https://docs.near.org/ .

**Comment by vlmoon99** [comment]
The most important concepts which you need to understand its : 1.How Account system works + how keys works . 2.How transaction flow works , 3. How smart contract calls works , and I think that all what you need, on the flutter chain side you can do anything what you want (beside staking) on near , so as I said earlier , if you have some question, feel free to ask

**Comment by caelum0x** [comment]
Hey I write you in telegram I will be very aprecciate it if you can help me
about it

23 Nis 2024 Sal, saat 12:42 tarihinde Vladyslav ***@***.***>
şunu yazdı:
