### ISSUE TITLE
Amount transformer error

### ISSUE THREAD

**Issue by amilkar97** [vlmoon99/flutterchain#6]
I have an account with balance of 0.02 Near, so when I try to get balance it throw me error in the method "static String yoctoNearToNear(String yoctoNearAmount)"

The network response is succesfully:
**Get response status code(200)Response body ({jsonrpc: 2.0, result: {amount: 20000000000000000000000, block_hash: ErnpsB3LVDtQVG18wZDXbBp5y54byvj6hWKZQqJKf8zo, block_height: 132312843, code_hash: 11111111111111111111111111111111, locked: 0, storage_paid_at: 0, storage_usage: 182}, id: dontcare})**

But the transformer throw:
RangeError (end): Invalid value: Not in inclusive range 0..23: -1

**Comment by vlmoon99** [comment]
I fixed it in 1.0.0-beta.9 version , @amilkar97 pls make update
